version: "3"
services:
  node-app:
    build: .
    ports:
      - "8000:8000"
    links:
      - mysql
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - ./.env
    volumes:
      - mysql-DB:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-DB:/data/redis-db

volumes:
  mysql-DB:
  redis-DB:
